const GAME_STATE_CONSTANT = [
  "ChoseSide",
  "ChoseMode",
  "StartClock",
  "Running",
  "GameOver",
  "SteelMate",
  "Victory",
  "Forfeit",
  "Streaming",
  "Practicing",
  "End",
  "Spectating",
  "Practice",
  "Paused",
  "Resumed",
  "Replay",
  "ReplayEnd",
  "ReplayPaused",
  "ReplayResumed",
  "ReplayStart",
  "PracticeInit",
  "ChoseSidePractice",
  "ChoseModePractice",
  "StartClockPractice",
  "ChoseSideRecordPractice",
  "ChoseModeRecordPractice",
  "StartClockRecordPractice",
  "RunningRecordPractice",
  "PracticeEnd",
  "RunningPractice",
  "RecordPractice",
  "RecordPracticeInit",
  "RecordPracticeEnd",
  "ChoseSideAI",
  "ChoseModeAI",
  "StartClockAI",
  "RunningAI",
  "",
  "ChoseSideRecordOpening",
  "ChoseModeRecordOpening",
  "StartClockRecordOpening",
  "RunningRecordOpening",
];

export const GAME_STATE_CONSTANT_PRACTICE = [
  "ChoseSideRecordOpening",
  "ChoseModeRecordOpening",
  "StartClockRecordOpening",
  "RunningRecordOpening",
  "RecordPractice",
];

export default GAME_STATE_CONSTANT;
